
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyyjftjqinrihdbyeyoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95eWpmdGpxaW5yaWhkYnlleW9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNjY2NzIsImV4cCI6MjA2NTY0MjY3Mn0.yurAGNSyapuMYawwLVHVXP56yulLczELRZ40uD4_jpw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
